apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: openapi-python-flask
spec:
  location: us-east1  # Replace with your preferred GCP region
  projectRef:
    external: projects/thomasscothamilton
  template:
    containers:
    - image: us-east1-docker.pkg.dev/thomasscothamilton/openapi-python-flask/openapi-python-flask
      ports:
      - containerPort: 8080
  traffic:
  - latestRevision: true
    percent: 100
