#
# TODO: Add secret https://cloud.google.com/config-connector/docs/reference/resource-docs/run/runservice
#
---
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}
spec:
  location: {{ .Values.location }}
  projectRef:
    external: projects/{{ .Values.projectRef }}
  template:
    containers:
    - image: {{ .Values.image }}
      ports:
      - containerPort: {{ .Values.containerPort }}
      volumeMounts:
        - name: {{ .Values.nameOverride | default .Chart.Name }}-volume
          mountPath: "/cloudsql"
    volumes:
     - name: {{ .Values.nameOverride | default .Chart.Name }}-volume
       cloudSqlInstance:
         instances:
           - name: {{ .Values.nameOverride | default .Chart.Name }}-cloudsql-instance