#
# TODO: Add secret https://cloud.google.com/config-connector/docs/reference/resource-docs/run/runservice
#
---
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  launchStage: "GA"
  location: {{ .Values.location }}
  projectRef:
    external: projects/{{ .Values.projectRef }}
  template:
    containerConcurrency: 80
    containers:
      - image: >-
          us-east1-docker.pkg.dev/thomasscothamilton/openapi-python-flask/openapi-python-flask
        ports:
          - containerPort: 8080
            name: http1
        resources:
          cpuIdle: true
          limits:
            cpu: 1000m
            memory: 512Mi
    scaling:
      maxInstanceCount: 100
    serviceAccountRef:
      external: 435144390383-compute@developer.gserviceaccount.com
    timeout: 300s
