apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}
spec:
  location: {{ .Values.location }}
  projectRef:
    external: projects/{{ .Values.projectRef }}
  template:
    containers:
    - image: {{ .Values.image }}
      ports:
      - containerPort: {{ .Values.containerPort }}