---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  name: cloudsql-db-password
spec:
  enabled: true
  secretData:
    valueFrom:
      secretKeyRef:
        key: secretData
        name: cloudsql-db-password
  secretRef:
    name: cloudsql-db-password
# kubectl create secret generic my-secret-data --from-literal=value="$(gcloud secrets versions access latest --secret=cloudsql-db-password)"
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: cloudsql-db-password
spec:
  replication:
    automatic: true