from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model import Model
from server import util


class Document(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None, content=None):  # noqa: E501
        """Document - a model defined in OpenAPI

        :param id: The id of this Document.  # noqa: E501
        :type id: str
        :param title: The title of this Document.  # noqa: E501
        :type title: str
        :param content: The content of this Document.  # noqa: E501
        :type content: str
        """
        self.openapi_types = {
            'id': str,
            'title': str,
            'content': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'content': 'content'
        }

        self._id = id
        self._title = title
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'Document':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Document of this Document.  # noqa: E501
        :rtype: Document
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Document.


        :return: The id of this Document.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Document.


        :param id: The id of this Document.
        :type id: str
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Document.


        :return: The title of this Document.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Document.


        :param title: The title of this Document.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def content(self) -> str:
        """Gets the content of this Document.


        :return: The content of this Document.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this Document.


        :param content: The content of this Document.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content
